#!/bin/bash
# Storyboard auto-sync — runs every 15 min via LaunchAgent
#
# SCOPED: only ever touches legacy session data files.
# NEVER stages or commits anything in apps/, supabase/, infra/, browser-extension/.
# Safe to run from any working directory state.

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────

# Support both the old and new repo paths
if [ -d "/Users/sainath/Downloads/CODA/storyboard/storyboard" ]; then
  REPO="/Users/sainath/Downloads/CODA/storyboard/storyboard"
elif [ -d "/Users/oskarpeterson/Documents/AI/AGENCY /storyboard" ]; then
  REPO="/Users/oskarpeterson/Documents/AI/AGENCY /storyboard"
else
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: cannot find repo directory" >&2
  exit 1
fi

LOG="$REPO/legacy/storyboard/auto-sync.log"

# Rotate log if > 1MB
if [ -f "$LOG" ] && [ "$(wc -c < "$LOG")" -gt 1048576 ]; then
  mv "$LOG" "${LOG}.bak"
fi

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG"; }

log "Auto-sync triggered"
cd "$REPO" || { log "ERROR: cannot cd to $REPO"; exit 1; }

# ── Safety check ──────────────────────────────────────────────────────────────
# Abort if key monorepo directories are missing — something is wrong with the
# working tree and we must NOT commit or push in this state.

for PROTECTED in apps supabase infra; do
  if [ ! -d "$PROTECTED" ]; then
    log "ABORT: protected directory '$PROTECTED' is missing — refusing to sync"
    log "       Run 'git status' and 'git pull origin main' to fix the working tree first"
    exit 1
  fi
done

# ── Fetch latest from remote ──────────────────────────────────────────────────

git fetch origin main --quiet 2>> "$LOG" || { log "WARNING: git fetch failed, skipping"; exit 0; }

# ── Stage ONLY scoped session files ──────────────────────────────────────────
# Explicit paths only — never `git add -A` or `git add .`

STAGED=0

# Carry-forward briefs (generated by Cowork)
if [ -d "legacy/storyboard/carry-forward-briefs" ]; then
  git add legacy/storyboard/carry-forward-briefs/ 2>/dev/null && STAGED=1
fi

# Session log (legacy data, root level — kept for backwards compat)
if [ -f "session-log.json" ]; then
  git add session-log.json 2>/dev/null && STAGED=1
fi

# Legacy session log inside the legacy dir
if [ -f "legacy/storyboard/session-log.json" ]; then
  git add legacy/storyboard/session-log.json 2>/dev/null && STAGED=1
fi

# ── Validate nothing dangerous is staged ─────────────────────────────────────
# Count how many files are being DELETED in the staged diff.
# More than 5 deletions is almost certainly a wipe — abort.

DELETIONS=$(git diff --cached --name-only --diff-filter=D | wc -l | tr -d ' ')
if [ "$DELETIONS" -gt 5 ]; then
  log "ABORT: $DELETIONS deletions staged — this looks like an accidental wipe"
  log "       Staged deletions:"
  git diff --cached --name-only --diff-filter=D | while read -r f; do log "         - $f"; done
  git reset HEAD -- . 2>/dev/null
  exit 1
fi

# ── Commit if there's anything new ───────────────────────────────────────────

if git diff --cached --quiet; then
  log "Nothing to commit — session data unchanged"
else
  COUNT=$(git diff --cached --name-only | wc -l | tr -d ' ')
  git commit -m "Auto-sync: session data $(date '+%Y-%m-%d %H:%M') ($COUNT file(s))" >> "$LOG" 2>&1
  log "Committed $COUNT session file(s)"
fi

# ── Push only if we're ahead of remote ───────────────────────────────────────

LOCAL=$(git rev-parse HEAD 2>/dev/null)
REMOTE=$(git rev-parse origin/main 2>/dev/null)

if [ "$LOCAL" != "$REMOTE" ]; then
  # Final safety: refuse to push if our HEAD would delete monorepo dirs vs remote
  REMOTE_HAS_APPS=$(git ls-tree --name-only origin/main | grep "^apps$" || true)
  LOCAL_HAS_APPS=$(git ls-tree --name-only HEAD | grep "^apps$" || true)

  if [ -n "$REMOTE_HAS_APPS" ] && [ -z "$LOCAL_HAS_APPS" ]; then
    log "ABORT: remote has apps/ but local HEAD does not — refusing to push a wipe"
    log "       Run 'git pull --rebase origin main' to sync first"
    exit 1
  fi

  log "Pushing to origin/main..."
  git push origin main >> "$LOG" 2>&1 && log "Push complete" || log "WARNING: push failed"
else
  log "Already up-to-date with remote"
fi
